import { Inter } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/Navbar";
import Header from "@/components/Header";
import Subscribe from "@/components/Subscribe";
import Footer from "@/components/Footer";
import { Suspense } from "react";
import Loading from "@/components/Loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Header />
        <Suspense fallback={<Loading />}>
          <main>
            <section className="w-11/12 lg:w-10/12 max-w-7xl mx-auto py-10">
              {children}
            </section>
            <Subscribe />
          </main>
        </Suspense>

        <Footer />
      </body>
    </html>
  );
}
